version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Pre-build phase started
      - java -version
      - mvn -version
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Copying built files to S3
      - aws s3 cp target/stock-advisor-0.0.1-SNAPSHOT.jar s3://${S3_BUCKET}/

artifacts:
  files:
    - target/stock-advisor-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/**/*
  discard-paths: no

cache:
  paths:
    - '/root/.m2/**/*'