services:
  - type: web
    name: stock-advisor
    runtime: docker
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/stock-advisor-0.0.1-SNAPSHOT.jar
    envVars:
      - key: ALPHA_KEY
        sync: false
      - key: OPENAI_KEY
        sync: false